### ISSUE TITLE
Potential issue in Atkinson 2015 verification table?

### ISSUE THREAD

**Issue by CB-quakemodel** [bakerjw/GMMs#1]
Assuming the verification table for Atkinson 2015 corresponds to the latest implementation in the GMMs repo for this model  where the alternative effective depth function is considered (as outlined in the documentation at the top of the script), I think this verification table might be incorrect (at least based on tests against my oq-engine implementation). Plotting of the intensity values vs rhypo for some magnitudes from the verification table in this repository shows that a lower intensity value is observed per unit distance, whereas the opposite would be expected with the alternative effective depth function (as observed in the original paper and trellis plots generated using the oq-engine implementation).

Here is some plots using the verification tables generated by the repo code:
![image](https://github.com/bakerjw/GMMs/assets/119606956/00165fe7-1ead-49db-b746-10148402d4fa)

And here is what I think should be expected based on paper, and observed using the oq-engine implementation:
![TrellisPlots](https://github.com/bakerjw/GMMs/assets/119606956/8cb197c7-0a88-42b3-923b-48ef02183384)

Thanks for any checking which can be performed regarding this!

**Comment by bakerjw** [comment]
Thank you for reaching out if you think there is an issue. I'm struggling to understand what "a lower intensity value is observed per unit distance" means. And I'm not sure what to make of the plots, as the plots are for differing magnitudes, and use differing distance metrics on the horizontal axis. If you could provide a more direct comparison to indicate what problem you think exists, we'll be happy to look into it.

**Comment by CB-quakemodel** [comment]
Thanks very much for your quick response. I will generate a more direct comparison as soon as possible to better demonstrate the (potential) issue.
